//%attributes = {"shared":true}
C_TEXT:C284($1)
C_TEXT:C284($2)
C_TEXT:C284($3)
C_TEXT:C284($4)
C_LONGINT:C283($5)

SET ENVIRONMENT VARIABLE:C812("XCEL_WORKBOOK_NAME"; $1)
SET ENVIRONMENT VARIABLE:C812("XCEL_SHEET_NAME"; $2)
SET ENVIRONMENT VARIABLE:C812("XCEL_SOURCE"; $3)
SET ENVIRONMENT VARIABLE:C812("XCEL_RANGE"; $4)
SET ENVIRONMENT VARIABLE:C812("XCEL_AUTOFILL_TYPE"; String:C10($5))

XCEL_util_EXECUTE("range_autofill")