//%attributes = {"shared":true}
C_TEXT:C284($1)
C_TEXT:C284($2)
C_TEXT:C284($3)
C_POINTER:C301($4)

SET ENVIRONMENT VARIABLE:C812("XCEL_WORKBOOK_NAME"; $1)
SET ENVIRONMENT VARIABLE:C812("XCEL_SHEET_NAME"; $2)
SET ENVIRONMENT VARIABLE:C812("XCEL_RANGE"; $3)

C_LONGINT:C283($i)

For ($i; 1; Size of array:C274($4->))
	SET ENVIRONMENT VARIABLE:C812("XCEL_VALUE"+String:C10($i); $4->{$i})
End for 

XCEL_util_EXECUTE("range_set_value_array")