//%attributes = {"shared":true}
C_TEXT:C284($1)
C_LONGINT:C283($2)
C_TEXT:C284($3)

SET ENVIRONMENT VARIABLE:C812("XCEL_WORKBOOK_NAME"; $1)
SET ENVIRONMENT VARIABLE:C812("XCEL_WINDOW_NUMBER"; String:C10($2))
SET ENVIRONMENT VARIABLE:C812("XCEL_WINDOW_CAPTION"; $3)

XCEL_util_EXECUTE("window_set_caption")