//%attributes = {"shared":true}
C_TEXT:C284($1)
C_TEXT:C284($2)
C_TEXT:C284($3)
C_LONGINT:C283($4)
C_LONGINT:C283($5)
//set the range as picture to pasteboard
SET ENVIRONMENT VARIABLE:C812("XCEL_WORKBOOK_NAME"; $1)
SET ENVIRONMENT VARIABLE:C812("XCEL_SHEET_NAME"; $2)
SET ENVIRONMENT VARIABLE:C812("XCEL_RANGE"; $3)
SET ENVIRONMENT VARIABLE:C812("XCEL_PICTURE_APPEARANCE"; String:C10($4))
SET ENVIRONMENT VARIABLE:C812("XCEL_PICTURE_FORMAT"; String:C10($5))

XCEL_util_EXECUTE("range_copy_picture")